from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.base import Base


class DynamicQuestionLog(Base):
    """A durable record of every question the chat pipeline ever asked —
    whether generated by chat_gpt_mediator.assess_and_generate_question
    (source="gpt_generated") or picked from the existing conversation_engine.
    QUESTIONS/DECISION_SLOTS catalogue (source="deterministic_fallback") —
    together with the user's answer once given. See the personal-astrologer
    chat upgrade plan's Phase 6: distinct from ConversationState.data, which
    only ever stores a slot ID/position for THIS conversation's live pending
    question, never the question text or answer itself. This table is what
    lets a later conversation (or app.services.dynamic_question_service's
    QuestionPatternStats aggregation) see what was actually asked and
    learned, long after ConversationState's own row has moved on."""

    __tablename__ = "dynamic_question_log"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    rishi_id: Mapped[str] = mapped_column(String(32), default="", server_default="")

    # The active category/decision type when this was asked (the "intent").
    category: Mapped[str] = mapped_column(String(64))
    # A finer-grained thing than category, e.g. "business_category_
    # suitability" — null for a plain DECISION_SLOTS-style question with no
    # sub-intent of its own.
    sub_intent: Mapped[str | None] = mapped_column(String(64), nullable=True)

    question_text: Mapped[str] = mapped_column(Text)
    # career | business | money | relationships | family | goals |
    # preferences | identity — the same VALID_DOMAINS life_context_service
    # already enforces; assess_and_generate_question's own output is bounded
    # to these before a row is ever written here.
    target_domain: Mapped[str] = mapped_column(String(32))
    target_key: Mapped[str] = mapped_column(String(64))
    # True when target_key wasn't already a known DECISION_SLOTS/life_context
    # key at the time this was asked — lets later analysis distinguish a
    # genuinely new information requirement from a re-ask of an existing one.
    is_novel_concept: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0")
    source: Mapped[str] = mapped_column(String(24))  # gpt_generated | deterministic_fallback

    answer_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    # The value actually written to LifeContextItem for this answer, if any
    # — kept alongside the raw answer_text since normalization (e.g.
    # trimming a self-referential prefix) can differ from what was typed.
    normalized_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Confidence in the ANSWER's usability (high/medium/low) — deliberately
    # NOT astrology confidence, and never rendered to the user.
    confidence: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # current | historical — mirrors LifeContextItem's own active/superseded
    # distinction for this specific question+answer pair, so a later
    # re-ask of the same concept doesn't leave two "current" rows.
    status: Mapped[str] = mapped_column(String(16), default="current", server_default="current")

    asked_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index("ix_dynamic_question_log_user_category", "user_id", "category"),
    )
