"""important_dates

Revision ID: ceaacb6bca36
Revises: 21df212bca39
Create Date: 2026-09-21 14:12:19.417287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaacb6bca36'
down_revision: Union[str, Sequence[str], None] = '21df212bca39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_important_dates_user_id'), 'important_dates', ['user_id'], unique=False)
    op.create_index('ix_important_dates_user_status', 'important_dates', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping the 'life_states_user_id_key'
    # unique constraint — pre-existing, unrelated drift between the
    # SQLAlchemy model and the actual Postgres schema (nothing to do with
    # this migration). Removed deliberately, same as the prediction_feedback
    # migration (Phase 2) — dropping it would remove the one-row-per-user
    # guarantee on life_states.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_important_dates_user_status', table_name='important_dates')
    op.drop_index(op.f('ix_important_dates_user_id'), table_name='important_dates')
    op.drop_table('important_dates')
    # ### end Alembic commands ###
