"""life_state_housing_fields

Revision ID: cf01ea8ff52b
Revises: ceaacb6bca36
Create Date: 2026-09-21 16:14:32.083133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf01ea8ff52b'
down_revision: Union[str, Sequence[str], None] = 'ceaacb6bca36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_states', sa.Column('housing_status', sa.String(length=16), nullable=True))
    op.add_column('life_states', sa.Column('planning_property_purchase', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('life_states', sa.Column('has_home_loan', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping the 'life_states_user_id_key'
    # unique constraint — pre-existing, unrelated drift between the
    # SQLAlchemy model and the actual Postgres schema (every prior migration
    # in this project has had to strip this same proposal). Removed
    # deliberately — dropping it would remove the one-row-per-user guarantee
    # on life_states, unrelated to this migration's purpose.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('life_states', 'has_home_loan')
    op.drop_column('life_states', 'planning_property_purchase')
    op.drop_column('life_states', 'housing_status')
    # ### end Alembic commands ###
